### PR TITLE
Check the correct variable for encrypted pools in TskAutoDb::addUnallocFsSpaceToDb

### LINKED ISSUE #3128: Wrong variable checked for encrypted pool flag in TskAutoDb::addUnallocFsSpaceToDb
When compiling with C++20, the following warning is emitted:
```
tsk/auto/auto_db.cpp: In member function 'TSK_RETVAL_ENUM TskAutoDb::addUnallocFsSpaceToDb(size_t&)':
tsk/auto/auto_db.cpp:1401:57: error: bitwise operation between different enumeration types 'TSK_VS_PART_FLAG_ENUM' and 'TSK_POOL_VOLUME_FLAGS' is deprecated [-Werror=deprecated-enum-enum-conversion]
 1401 |                                 if (curVsPartInfo.flags & TSK_POOL_VOLUME_FLAG_ENCRYPTED) {
      |                                     ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
The problem here is that `curVsPartInfo.flags` and `TSK_POOL_VOLUME_FLAG_ENCRYPTED` are not from the same enum; it makes no sense to check for `TSK_POOL_VOLUME_FLAG_ENCRYPTED` in `curVsPartInfo.flags` because the latter has nothing to do with pools at all.

### PR DESCRIPTION
**Pull request by uckelman-sf**
`TSK_VS_PART_INFO::flags` is a `TSK_VS_PART_FLAG_ENUM`, not a `TSK_POOL_VOLUME_FLAGS`, so it makes no sense to check for `TSK_POOL_VOLUME_FLAG_ENCRYPTED` in it. Presumably the correct variable to test is `vol_info->flags`, from the `TSK_POOL_VOLUME_INFO`.

Fixes #3128.

### CODE REVIEW

**Comment by uckelman-sf** [comment]
@simsong Ready for review.

File: tsk/auto/auto_db.cpp [hunk 1]
```diff
@@ -1398,7 +1398,7 @@ TSK_RETVAL_ENUM TskAutoDb::addUnallocFsSpaceToDb(size_t & numFs) {
 
                             }
                             else {
-                                if (curVsPartInfo.flags & TSK_POOL_VOLUME_FLAG_ENCRYPTED) {
+                                if (pool->vol_list->flags & TSK_POOL_VOLUME_FLAG_ENCRYPTED) {
                                     tsk_error_reset();
```
Comment (simsong) [inline tsk/auto/auto_db.cpp:1402]: Huh.

**Review by simsong — APPROVED** [review]

**Comment by simsong** [comment]
With all of the bugs you've been fixing, it's pretty amazing that TSK was working at all...
